import { useAuth0 } from "@auth0/auth0-react";
import { getAccessToken, useUser } from "@auth0/nextjs-auth0";
import {
  Box,
  Button,
  CircularProgress,
  styled,
  TextField,
} from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Layout from "../components/layout/Layout";

const Hero = styled("div")(
  ({ theme }) =>
    `align-items: center;
    border: 1px solid pink;
    box-sizing: border-box;
    display: grid;
    grid-template-columns: 1fr;
    margin-top: 3.5rem;
    border-radius: 1.5rem;
    padding: 3rem 2rem;
    font-family: ${theme.typography.fontFamily}
`
);
const CenteredContainer = styled("div")(
  ({ theme }) =>
    `
    margin-left: auto;
    margin-right: auto;
    max-width: 768px;
    padding-bottom: 3rem;
    width: 100%;
`
);

const HeroText = styled("div")(
  ({ theme }) =>
    `
    font-size: 1.5rem;
    line-height: 2rem;
`
);

const Content = () => {
  const [num, setNum] = useState("");
  const user = useUser();
  const auth = useAuth0();
  console.log(user.user);
  console.log(auth);


  const handleClick = async () => {
    alert("clicked" + auth.user?.email);

    const foo = await fetch("/api/services", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ timeSlot: "1200", phone: num }),
    });
    const j = foo.json();
    console.log(j);
  };

  const handleAuthClick = async () => {
    await auth.loginWithPopup();
    console.log(auth);
    
    const idToken = await auth.getIdTokenClaims();
    console.log({idToken});
    
    const response = await fetch(
      "https://bpqc2pxzub.execute-api.ap-southeast-2.amazonaws.com/dev/services/9ed6dc2c-5c96-4218-9ac6-dde908ff4c65/book",
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${idToken?.__raw}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ timeSlot: "1200", phone: num }),
      }
    );
    const products = await response.json();
    console.log(products);

    auth.logout();
  };

  return (
    <CenteredContainer>
      <Hero>
        nextjs auth example
        <HeroText>Premium "I love you" message</HeroText>
        <br />
        <TextField
          label="Phone number"
          placeholder="04"
          sx={{ fontSize: 50 }}
          value={num}
          onChange={(e) => setNum(e.target.value)}
        />
        <br />
        <Button
          variant="contained"
          color="secondary"
          onClick={handleClick}
          disabled={!user.user?.sub}
        >
          Become mine
          {user.isLoading && <CircularProgress />}
        </Button>
        <Box>
          {user.user?.sub ? (
            <>
              Logged in as: {user.user?.nickname}
              {" | "}
              <a
                href="/api/auth/logout"
                style={{ textDecoration: "underline" }}
              >
                Logout
              </a>
            </>
          ) : (
            <a href="/api/auth/login">Login </a>
          )}
        </Box>
      </Hero>

      <Hero>
        react auth example
        <HeroText>Premium "I love you" message</HeroText>
        <br />
        <TextField
          label="Phone number"
          placeholder="04"
          sx={{ fontSize: 50 }}
          value={num}
          onChange={(e) => setNum(e.target.value)}
        />
        <br />
        <Button variant="contained" color="secondary" onClick={handleAuthClick} >
          Login and Post
        </Button>
        <Box>
          {auth.user?.email ? (
            <>
              Logged in as: {auth.user?.email} |{" "}
              <Button onClick={() => auth.logout()}>Logout</Button>
            </>
          ) : (
            <Button onClick={() => auth.loginWithPopup()}>Login</Button>
          )}
        </Box>
      </Hero>
    </CenteredContainer>
  );
};

const Home: NextPage = () => {
  return (
    <Layout title={"Premium e-Gaz"}>
      <Head>
        <title>Premium e-thot</title>
        <meta name="description" content="Generated by your favourite e-gaz" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Content />
    </Layout>
  );
};

export default Home;
